#!/bin/bash

# $1 = grace period
# $2 = target pid

function uid_of() {
	cat /proc/$1/status | grep "^Uid:\s" | cut -f 2
}

sleep $1

if [ ! -d /proc/$2 ]; then
	exit 1
fi

if [ $(uid_of $2) -ne $(id -u) ]; then
	exit 2
fi

kill -TERM $2 >/dev/null 2>&1
